#pragma once

#undef UNI_FUNCTION
#undef UNI_FORCE_ASSERTS
#undef UNI_DISABLE_ASSERTS
#undef UNI_ENABLE_DYNAMIC_ASSERT_HANDLER
#undef UNI_SYSTEM_ASSERT_HEADER
#undef UNI_SYSTEM_ASSERT
#undef UNI_ENABLE_STATIC_ASSERT_HANDLER
