language: cpp
sudo: required
services:
    - docker

before_install:
    - docker pull lasote/conangcc5

script:
    - docker run -v$(pwd):/home/conan/project --rm lasote/conangcc5 conan create ./project uniassert/testing
